### ISSUE TITLE
I'm getting this error *"Hoa main file (Core.php) must be included once."*

### ISSUE THREAD

**Issue by YnievesDotNet** [hoaproject/Core#100]
How I can fix this??

**Comment by Jir4** [comment]
It's related to hoaproject/Central#32

**Comment by Hywan** [comment]
Actually, I am not sure. @YnievesDotNet What are your dependencies?

**Comment by YnievesDotNet** [comment]
"hoa/cli": "~1.0",
"hoa/websocket": "~2.0"

**Comment by Hywan** [comment]
@YnievesDotNet Can you retry now please?

**Comment by YnievesDotNet** [comment]
i test now

El 14-ene-16 a las 5:42 PM, Ivan Enderlin escribió:

> @YnievesDotNet https://github.com/YnievesDotNet Can you retry now 
> please?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/hoaproject/Core/issues/100#issuecomment-171805124.

## 

Yoinier Hernandez Nieves.
CEO YnievesDotNet
Tel: +53 3139 2210
Cel: +53 5347 1184

**Comment by YnievesDotNet** [comment]
now run fine, thanks.

**Comment by Hywan** [comment]
@Jir4 You were right!
