### ISSUE TITLE
mark as deprecated

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/Core#103]
hello,
I think we need to say in the readme that this is deprecated and on packagist https://packagist.org/packages/hoa/core too.

what do you think on that?

**Comment by Hywan** [comment]
Hello :-),

That's an excellent idea.

The `README.md` already has a section for that, see https://github.com/hoaproject/Core#warning.
The package has been marked as abandonned on Packagist, https://packagist.org/packages/hoa/core, and now suggests `hoa/consistency` instead. That's not totally true, but it is the closest in term of goals.
