### ISSUE TITLE
Set custom Hoa paths -> easy way? 

### ISSUE THREAD

**Issue by 1e1** [hoaproject/Core#30]
It should friendly create a method to redefine the main roots of the Hoa wrapper. 
```php
$hoa = Hoa\Core\Core::getInstance();
$hoa->getParameters()->setParameter('root.application', __DIR__);
$hoa->getParameters()->setParameter('root.data', __DIR__ . DS . 'Data');
$hoa->setProtocol();
```

What do you think about something like `unresolve($data, $application=null, $hoa=null);`?

**Comment by vonglasow** [comment]
@Hywan can we close this issue as Hoa\Core is no longer maintained ?

**Comment by Hywan** [comment]
Sure!
@1e1 If this issue is still valid with [the `Hoa\Protocol` library](https://github.com/hoaproject/Protocol), please, reopen it there.
