### ISSUE TITLE
Hoa\Core should NEVER edit php configuration.

### ISSUE THREAD

**Issue by stephpy** [hoaproject/Core#61]
We should avoid automatic definition of what we estimate as a good thing [like this](https://github.com/hoaproject/Core/blob/master/Core.php#L181-L188)

It should be a command which pilot user to edit its configuration to use good thinkgs (UTC as timezone, etc....)

This command could be part of Hoa\Core ? 

Thought ?

**Comment by Jir4** [comment]
Solved by the core split isn't it ?

**Comment by Hywan** [comment]
Yup!

**Comment by Hywan** [comment]
Good catch :+1:

**Comment by Hywan** [comment]
So far, the prelude does not change `mb_*` configuration: https://github.com/hoaproject/Consistency/blob/7656b971a8248a8d314ed0c5bb0668936438f62a/Prelude.php.

**Comment by Jir4** [comment]
I checked it before posting ^^

**Comment by Hywan** [comment]
Just for the record and for @stephpy :-).

**Comment by Jir4** [comment]
:+1:
