### ISSUE TITLE
Hint IDEs about property.

### ISSUE THREAD

**Issue by Metalaka** [hoaproject/Core#65]
Most of Hoa's `@var` tag in property phpDoc don't use the right syntax (according to [phpdoc.org](http://phpdoc.org/docs/latest/references/phpdoc/tags/var.html) & IDEs hints).
The class name shouldn't be written before the var type.

eg:
```php
namespace Hoa\Core\Protocol;

class Protocol {
    /**
     * Collections of sub-components.
     *
     * @var \Hoa\Core\Protocol array
     */
    private $_components   = array();
}
```
IDEs provide hints for `\Hoa\Core\Protocol`, but the property is an array...

**Comment by Metalaka** [comment]
Fixed by `hoa devtools:cs` in [Hoa/Devtools/Resource/PHPCSFixer/Fixer/PhpdocVar.php](https://github.com/hoaproject/Devtools/blob/b6b8c8421a0d630a7c798e425f10048d8466080e/Resource/PHPCSFixer/Fixer/PhpdocVar.php)

**Comment by Hywan** [comment]
Cool :+1:
