### ISSUE TITLE
hoa break when installed globaly

### ISSUE THREAD

**Issue by mikeSimonson** [hoaproject/Core#67]
Hi,

The main hoa file in the Bin folder does not require the autoload from composer properly.

Here is an example.
https://github.com/tomzx/php-semver-checker/blob/master/bin/php-semver-checker

**Comment by Hywan** [comment]
@mikeSimonson How do you install Hoa? Can you me an example please because I am not able to reproduce the bug. As far as I can see, https://github.com/hoaproject/Core/blob/9fa825864a091bdb31cc4e53e086306abece558e/Bin/Hoa.php#L46-L52, Composer's autoloader is well-included :-/.

**Comment by mikeSimonson** [comment]
I installed https://github.com/Halleck45/PhpMetrics/ globally with : 
```sh
composer global require Halleck45/PhpMetrics
```
It installed hoa because it's a dependency.
But hoa is not working on it's own because it try to require the autoload.php as if it was installed in a project build with composer.
Here when installed globally the autolad.php is not in a vendor directory and it's one more level up in the directory structure.

If you look at the example I give in my first message you will see that there are 2 path indicated to find the autoload.php

**Comment by Hywan** [comment]
@mikeSimonson Hmm interesting. Could you make a PR?
