### ISSUE TITLE
Setlocal issues in core

### ISSUE THREAD

**Issue by th3fallen** [hoaproject/Core#77]
https://github.com/hoaproject/Core/blob/master/Core.php#L173 is causing language issues over at OC is there  a possible workaround for this? we've found that commenting this line out resolves the issue with using non-ASCII Chars

Not sure the impact that could have in other areas though?

**Comment by Hywan** [comment]
Related to https://github.com/hoaproject/Core/issues/61.

**Comment by Hywan** [comment]
I am going to fix this next week maximum.

**Comment by th3fallen** [comment]
any updates here?

**Comment by Hywan** [comment]
@th3fallen The `setlocale` has been introduced by @1e1 with https://github.com/hoaproject/Core/commit/9525930f01c734ac3dcec2d5aee6ee3e9f616023. What do you think? How to prevent the bug he mentionned?
