### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Core#80]
Hey :-),

PHP7 introduces some BC breaks and we have to track and fix them before end of June.
Here is the official list that changed: https://github.com/php/php-src/blob/master/UPGRADING.

How to track them?
  1. run `hoa test:run --all` often,
  2. run
```sh
find . -name "Bool\.php" -o \
    -name "Int\.php" -o \
    -name "Float\.php" -o \
    -name "String\.php" -o \
    -name "Null\.php" -o \
    -name "False\.php" -o \
    -name "True\.php" -o \
    -name "Resource\.php" -o \
    -name "Object\.php" -o \
    -name "Mixed\.php" -o \
    -name "Numeric\.php"
```
until it results nothing,
  3. track some place where `BaseException` must be used instead of `Exception`,
  4. add retro-compatibility with prior versions of PHP7.

**Comment by Pierozi** [comment]
@Hywan what is concern about `BaseEngine`

**Comment by Hywan** [comment]
@Pierozi Because with have an error handler. And it can receive a `BaseException`. Sorry, yes, it's a typo. Fixed.
