### ISSUE TITLE
Hoa/Core errors when loaded twice

### ISSUE THREAD

**Issue by evert** [hoaproject/Core#90]
In our scenario, we have a project that depends on Hoa\Bench.

We also have globally installed packages (`composer global`), in particular phpunit and other Hoa dependencies.

The `phpunit` binary is executed globally for our package. This means that there are two composer autoloaders active, each load a copy of `Hoa\Core`, even though the global one does not require it.

This causes this error:

```php
phpunit --configuration tests/phpunit.xml
Hoa main file (Core.php) must be included once.
```

The root cause for this, is that Core.php is loaded regardless of it it's ever used or not.

Source: https://github.com/fruux/sabre-vobject/issues/238

It would be nice if there is a solution to this =) Hope all is well!

**Comment by Hywan** [comment]
Hello :-),

If you replace https://github.com/hoaproject/Core/blob/master/Core.php#L52 by a simple `return` statement, does it work?

I am not it's going to be the solution. Just testing stuff.

**Comment by evert** [comment]
Confirmed to work for my use-case. Put that return statement a bit higher up though ;)

**Comment by Hywan** [comment]
@evert Yup sorry, here https://github.com/hoaproject/Core/blob/df1f75e6a98d52b879bf36bc1ea8744433458f09/Core.php#L46.

So it works. Great. But an exit seems better since it shows a unexpected workflow or file load. What do you think is better? Being silent is… good for new comers but not good to make something clean. It's always the “strict vs. friendly” debate…

Please @hoaproject/hoackers, raise your voice!

**Comment by harikt** [comment]
Actually why do you need to keep an exit or require in hoa itself ?
Why can't it be kept the responsibility of composer or other autoloaders to handle this ?

**Comment by Hywan** [comment]
@harikt Because if Composer or another project sucks at loading correctly different dependencies (I am not blaming anyone, it just happens sometimes), the developper will not notice. This `exit` is bad but it shows that something wrong is happening. It is a guard. But it makes the user experience bad sometimes and people are blaming Hoa at the end… which is really bad for us. We are the good guys here :-(.

**Comment by harikt** [comment]
@Hywan not sure what you mean by composer not loading correctly.

Do you have any example to show the psr-0, psr-4 autoloaders are not working correctly?

**Comment by Hywan** [comment]
See the usecase of @evert right above. It is possible to load the same file twice if present in two different locations (so it's not the same file but it contains the same content).

**Comment by harikt** [comment]
Actually that is a good point. But I have a doubt.

I hope we are using autoloader to load than requiring ourselves.

1 ) Assuming Hoa\Core\Core is the class trying to load.
2 ) Autoloader checks if class is loaded or not and try to load from ( global / different ) path.
3 ) It loads the file
4 ) Now we don't need to care the location of the file it loads right ?

May be I am missing something. Sorry if I am asking silly doubts just ignore and don't get frustrated with my comments.

Thank you.

**Comment by Hywan** [comment]
We load `Core.php` with the `files` Composer's property. So the `class_exists` is not used here.

**Comment by harikt** [comment]
Thank you for the clarification @Hywan .

**Comment by Hywan** [comment]
It's very close to what we talked about here: https://github.com/composer/composer/pull/3794.

**Comment by evert** [comment]
Wouldn't it be better though if Core is only loaded if it's actually used? This might be a larger change, but do you really need it? Perhaps some of it's functionality can be moved to functions that can get optionally included, on demand.

**Comment by harikt** [comment]
I agree with @evert here.

It seems to me ( blame me I don't really know if that breaks anything )  that we can include a file which have the functions defined below https://github.com/hoaproject/Core/blob/df1f75e6a98d52b879bf36bc1ea8744433458f09/Core.php#L474 .

And the class `Core` is just a psr-4  classloader. So I believe that change bring one thing, and we can make sure it is not loaded any where else. So many of the require will go away and giving the autoloader the complete control. There can be pitfalls though I am not seeing / experiencing.

**Comment by Hywan** [comment]
We heavily rely on the `hoa://` protocol and we need to register it automatically, so the `files` Composer's property is required. With the split of `Hoa\Core`, I am planning to create `Hoa/Protocol` and to `files` this library instead of the whole `Hoa\Core` code.

**Comment by ahungry** [comment]
This is broken when using HOA (2.0) under Symfony 2.8+ as a composer dependency (the Sensio installer for building the app/bootstrap.php.cache file will terminate early due to the HOA exit call).

I'm guessing it's because it see's 'HOA' defined more than once, as it gets redefined as the composer process continues to run.

I agree with adding a 'return', not an exit, or at the very least throwing an exception (so it can be left up to the programmer to catch it, or let it fall through and terminate with a stack trace).

Using a raw exit doesn't make sense.

Also, the error message is not good, it implies (to me) that the file was not included at all, when the intent is to inform the user that the file was included more than once.

It seems updating the hoa\websocket dependency to 3.x from 2.x fixes it, however remaining on the 2.x version, per semantic versioning, should be a viable option.  Was something changed that breaks backwards compatability with it?

**Comment by Hywan** [comment]
Hoa/Core has been split, see http://blog.hoa-project.net/posts/36-the-nucleus-releases-serie.html.

Please, can you test with `hoa/websocket` `~3.0`. I am guessing the issue will still be present. There was no BC break here as far as I know @ahungry.

What the `app/bootstrap.php.cache` file?

**Comment by Hywan** [comment]
Actually, we are now throwing an exception. No more `exit`. See https://github.com/hoaproject/Consistency/blob/c7919e409ca68858f8cceadb7565b9f622575249/Prelude.php#L42-L44.

**Comment by harikt** [comment]
@Hywan question why does it actually need the exception.. Isn't it can be dealt with composer? 

May be you are providing the whole library to be downloaded without composer ?

**Comment by harikt** [comment]
@Hywan never mind you have answered earlier to my same question :) . 

Sorry for the trouble. Just got the mail and was checking :) .

**Comment by Hywan** [comment]
No problem :-]. We are no longer checking if Hoa exists or not. We just let PHP cries out. We are just checking if Hoa can run now.

**Comment by takeit** [comment]
I'm getting this error now, instead of `Hoa main file (Core.php) must be included once.`

``` bash
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
PHP Warning:  stream_wrapper_register(): Protocol hoa:// is already defined. in /Library/WebServer/Documents/webrenderer/vendor/hoa/protocol/Wrapper.php on line 580
PHP Stack trace:
PHP   1. {main}() /Library/WebServer/Documents/webrenderer/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php:0
PHP   2. require_once() /Library/WebServer/Documents/webrenderer/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php:56
PHP   3. require() /Library/WebServer/Documents/webrenderer/app/autoload.php:9
PHP   4. ComposerAutoloaderInit3f3335623abaff7be0401e4c45c6e337::getLoader() /Library/WebServer/Documents/webrenderer/vendor/autoload.php:7
PHP   5. composerRequire3f3335623abaff7be0401e4c45c6e337() /Library/WebServer/Documents/webrenderer/vendor/composer/autoload_real.php:45
PHP   6. require() /Library/WebServer/Documents/webrenderer/vendor/composer/autoload_real.php:55
PHP   7. stream_wrapper_register() /Library/WebServer/Documents/webrenderer/vendor/hoa/protocol/Wrapper.php:580
```

**Comment by Hywan** [comment]
@takeit Can I see you `composer.json` please?

**Comment by Hywan** [comment]
@takeit There is a conflict between some versions. Someone on IRC just came with the same error.

**Comment by titolendable** [comment]
I am currently experiencing the same error reported by @takeit 

Here is a list of all the Hoa packages I am using on my Symfony 2.8 project:

hoa/compiler                                    2.15.10.29            The Hoa\Compiler library.
hoa/consistency                                 1.16.01.11            The Hoa\Consistency library.
hoa/core                                        2.15.11.09            The Hoa\Core library.
hoa/event                                       1.16.01.11            The Hoa\Event library.
hoa/exception                                   1.16.01.11            The Hoa\Exception library.
hoa/file                                        0.15.11.09            The Hoa\File library.
hoa/iterator                                    1.15.10.29            The Hoa\Iterator library.
hoa/math                                        0.15.10.26            The Hoa\Math library.
hoa/protocol                                    1.16.01.11            The Hoa\Protocol library.
hoa/regex                                       0.15.08.13            The Hoa\Regex library.
hoa/ruler                                       1.15.11.09            The Hoa\Ruler library.
hoa/stream                                      0.16.01.11            The Hoa\Stream library.
hoa/ustring                                     3.15.11.09            The Hoa\Ustring library.
hoa/visitor                                     1.15.08.17            The Hoa\Visitor library.

**Comment by harikt** [comment]
@titolendable how about edit `vendor/hoa/protocol/Wrapper.php` line [580](https://github.com/hoaproject/Protocol/blob/master/Wrapper.php#L580) with 

``` php
if (! in_array("hoa", stream_get_wrappers())) {
    stream_wrapper_register('hoa', 'Hoa\Protocol\Wrapper');
}
```

It may be just a temporary fix until @Hywan comes up with something.

**Comment by titolendable** [comment]
@harikt indeed that solves the problem, but I'd say that it is not very efficient, seems to me that the file is being loaded several times, that's why we are getting the problems in the first place, something that needs to be addressed. Let's wait for a fix to be released.

**Comment by harikt** [comment]
@titolendable sure. It probably need a require_once and that should solve. But I am unsure about the whole working.

**Comment by titolendable** [comment]
@harikt many thanks

**Comment by Hywan** [comment]
Actually, your dependencies are wrong. Yes, we still have “unstable” libraries marked as `0.*`, and it's annoying. We are working hard on this. However, you should have:

```
hoa/compiler ~3.0
hoa/consistency ~1.0
~~hoa/core~~
hoa/event ~1.0
hoa/exception ~1.0
hoa/file ~0.16
hoa/iterator ~2.0
hoa/math ~0.16
hoa/protocol ~1.0
hoa/regex ~0.16
hoa/ruler ~2.0
hoa/stream ~0.16
hoa/ustring ~4.0
hoa/visitor ~2.0
```

Can I see you `composer.json` file please?

**Comment by Hywan** [comment]
Running `composer update` creates this issue. You have to update your depdendencies manually (simply bump the `x` if > 0) and then run `composer update`.

**Comment by Hywan** [comment]
@harikt Your proposal, while potentially correct, creates another issue. If the `hoa://` is registered twice, it means that `hoa/core` is still present and it must not :-).

**Comment by takeit** [comment]
hey @Hywan  btw this is what I have in composer:

``` json
hoa/compiler                          2.15.10.29         The Hoa\Compiler library.
hoa/consistency                       dev-master c7919e4 The Hoa\Consistency library.
hoa/core                              dev-master acd3709 The Hoa\Core library.
hoa/event                             dev-master 74757b4 The Hoa\Event library.
hoa/exception                         dev-master fa4a964 The Hoa\Exception library.
hoa/file                              0.15.11.09         The Hoa\File library.
hoa/iterator                          1.15.10.29         The Hoa\Iterator library.
hoa/math                              0.15.10.26         The Hoa\Math library.
hoa/protocol                          dev-master 97a3335 The Hoa\Protocol library.
hoa/regex                             0.15.08.13         The Hoa\Regex library.
hoa/ruler                             1.15.11.09         The Hoa\Ruler library.
hoa/stream                            dev-master 06804e6 The Hoa\Stream library.
hoa/ustring                           3.15.11.09         The Hoa\Ustring library.
hoa/visitor                           1.15.08.17         The Hoa\Visitor library.
```

**Comment by harikt** [comment]
Hey @Hywan yes may be ... I was just figuring out via the error message :) . 

@takeit what you have provided is package information. If possible could you paste the exact composer.json file in the root of your repo?

So we can see how the library versions are mentioned in 

``` json
{
    "require": {
        "hoa/core": "1.*" 
       .....
    }
}
```

etc. Thank you.

**Comment by takeit** [comment]
Actually I require this lib: [halleck45/phpmetrics](https://github.com/Halleck45/PhpMetrics) (`"halleck45/phpmetrics": ">=1.2.0"`) and its causing mentioned by me issue. 

I see this library requires `"hoa/ruler": "~1.0",` See https://github.com/Halleck45/PhpMetrics/blob/master/composer.json#L36

**Comment by Hywan** [comment]
Yes, we have a fail in our dependencies because of `0.*` versions. phpmetrics should require `hoa/ruler` `~2.0` but it will drop PHP5.4. Or, it musts add constraints, sorry for that.

**Comment by Hywan** [comment]
See https://github.com/Halleck45/PhpMetrics/issues/173.

**Comment by Hywan** [comment]
Please, see https://github.com/hoaproject/Central/issues/32.

**Comment by Hywan** [comment]
@takeit Now it's fixed. Just run `composer update` or `composer install` and everything will be fine :-).

**Comment by takeit** [comment]
@Hywan it works fine now. Thanks a lot!
