### ISSUE TITLE
[meta] Split the core, next

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Core#97]
After #96, we must continue to split the core. Goal: Remove `Hoa\Core`.
We have to split `Hoa\Core\Parameter` and `Hoa\Core\Data`, and also `Hoa\Core\Core`. What is the strategy here? We must (i) find namings and (ii) find if they must exist (if they have a future). What do you think?

**Comment by Hywan** [comment]
* `Hoa\Core\Data` can be moved to `Hoa\Xyl`, the only place where we use it.
* `Hoa\Core\Core` can be removed totally.
* `Hoa\Core\Parameter` needs a better name. Any idea @hoaproject/hoackers?

**Comment by Pierozi** [comment]
`Hoa\Core\Parameter` to `Hoa\Core\Config` or `Hoa\Core\Constant` because roughly its value will not be changed after it's defined.

**Comment by Jir4** [comment]
i disagree, `Hoa\Core\Parameter` didn't just set constant. There's an interface used in several other rep.

**Comment by Hywan** [comment]
Back to #96 for a more comprehensive list of tasks.
